# Welcome messages for the login page
[welcome-messages]
messages = [
    "Welcome to Do! Please enter your username to continue.",
    "Hello there! Enter your username to get started with Do.",
    "Greetings! Type your username to begin your Do journey.",
    "Welcome! Enter your username to access your Do workspace.",
    "Hi there! Please provide your username to continue to Do.",
    "Ready to get organized? Enter your username to start.",
    "Welcome back! Please enter your username to continue.",
    "Let's get productive! Enter your username to begin.",
    "Do awaits! Please enter your username to continue.",
    "Hello! Type your username to access your Do workspace.",
    "Welcome to your productivity hub! Enter your username to continue.",
    "Glad to see you! Enter your username to get started.",
    "Ready to do? Enter your username to begin.",
    "Welcome to Do! Your username, please.",
    "Hello! Your Do workspace is ready. Enter your username to continue.",
    "Greetings! Your username will unlock your Do experience.",
    "Welcome! Your productivity journey begins with your username.",
    "Hi there! Enter your username to access your Do tools.",
    "Ready to organize your thoughts? Enter your username to begin.",
    "Welcome to Do! Please identify yourself with your username.",
    "Hello! Your Do workspace awaits. Enter your username to continue.",
    "Greetings! Please enter your username to access Do.",
    "Welcome aboard! Your username will get you started.",
    "Hi! Enter your username to begin your Do session.",
    "Ready to achieve more? Enter your username to start.",
    "Welcome to your personal productivity space! Enter your username to continue.",
    "Hello there! Your username is the key to your Do experience.",
    "Greetings! Enter your username to unlock your workspace.",
    "Welcome to Do! Please enter your username to get started.",
    "Hi! Your username will connect you to your Do environment.",
    "Ready for a productive session? Enter your username to begin.",
    "Welcome! Your Do journey starts with your username.",
    "Hello! Please enter your username to access your workspace.",
    "Greetings! Your username will unlock your Do tools.",
    "Welcome to your productivity partner! Enter your username to continue.",
    "Hi there! Your username is required to access Do.",
    "Ready to organize your tasks? Enter your username to start.",
    "Welcome to Do! Please provide your username to continue.",
    "Hello! Your username will connect you to your workspace.",
    "Greetings! Enter your username to begin using Do.",
    "Welcome! Your productivity tools await. Enter your username to continue.",
    "Hi! Please enter your username to access your Do environment.",
    "Ready to get things done? Enter your username to begin.",
    "Welcome to your personal assistant! Enter your username to continue.",
    "Hello there! Your username will unlock your Do experience.",
    "Greetings! Please enter your username to get started with Do.",
    "Welcome aboard! Your username is required to continue.",
    "Hi! Enter your username to access your personal workspace.",
    "Ready for a focused session? Enter your username to begin.",
    "Welcome to Do! Your username is the key to your experience."
]
