"""
This module contains the EmailAgent class for generating email content.
"""

from pydantic import BaseModel as PydanticModel, Field as PydanticField

from do.agents.base_agent import Agent
from do.db_models import User


class EmailHelperSuggestions(PydanticModel):
    """
    Model for email suggestions generated by the EmailAgent.

    This model contains the subject and message for an email, which are generated
    based on the user's request.

    Attributes:
        subject: The suggested email subject
        message: The suggested email body
    """
    subject: str = PydanticField(description="An appropriate email subject that is clear, concise, and relevant.")
    message: str = PydanticField(description="An email body that is professional, well-structured, and appropriate.")


class EmailAgent(Agent):
    """You are an email content generator for Do, a task management tool.
    Your purpose is to generate professional, well-structured email subjects and messages
    based on the context provided. You should create email content that is appropriate,
    clear, and effective for professional communication.

    Pay extra close attention to the intent of the user and the context provided.

    Guidelines:
    - Generate email subjects that are concise, clear, and relevant to the context
    - Create email body content that is professional, well-structured, and appropriate
    - Adapt the tone and style based on the context and project information provided
    - Include appropriate greetings and closings in the email body
    - Keep the content focused and relevant to the purpose of the email

    Tone:
    Professional, clear, and appropriate for business communication."""
    output_type = EmailHelperSuggestions

    def __init__(self, user: User):
        """
        Initialize the EmailAgent with user information.

        Args:
            user: The user for whom to generate email content
        """
        self.system_prompt = f"The current user is {user.username}.\n{self.system_prompt}"
        super().__init__()