apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: do-db-pvc
  namespace: 8ly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage 