---
apiVersion: v1
kind: Service
metadata:
    name: do-8ly-website
    namespace: 8ly
    labels:
        app: 8ly-do-website
        tier: frontend
spec:
    type: NodePort
    ports:
      - port: 8000
        name: http
    selector:
        app: 8ly-do-website
        tier: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: do-8ly-website
    namespace: 8ly
    labels:
        app: 8ly-do-website
    annotations:
        kubernetes.io/ingress.class: "traefik"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
    tls:
      - hosts:
        - do.8ly.xyz
        secretName: 8ly-do-website-cert
    rules:
      - host: do.8ly.xyz
        http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: do-8ly-website
                    port:
                      number: 8000
